project = "mood-270122"
region = "us-east1"
cluster_name_suffix = "cluster"
ip_range_pods = "pods"
ip_range_services = "services"
compute_engine_service_account = "1057705331610-compute@developer.gserviceaccount.com"
